# 1. Redirigir todo el tráfico inseguro (HTTP) a seguro (HTTPS)
server {
    listen 80;
    server_name nexovatech.com.co www.nexovatech.com.co;
    return 301 https://$host$request_uri;
}

# 2. Servidor Principal Seguro (HTTPS)
server {
    listen 443 ssl;
    server_name nexovatech.com.co www.nexovatech.com.co;

    # Rutas a los certificados que Certbot generó
    ssl_certificate /etc/letsencrypt/live/nexovatech.com.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nexovatech.com.co/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $request_uri $request_uri/ /index.html;
    }

    # Proxy para conectar con tu backend FastAPI
    location /api/ {
        proxy_pass http://nexova_backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}